---
- hosts: 127.0.0.1
  name: Remove NSX Deployment
  gather_facts: false
  vars_files: 
    - answerfile.yml

# Quick way is to add Extra_Vars for removal - (e.g. ansisble-playbook -e @answerfile-deployment.yml -e state="absent") - This will overwrite your answerfile state to absent vs persent
# Infrastructure Deployment # 

- import_playbook: playbooks/remove/01-remove-nsxmanager-edgeclusters.yml
- import_playbook: playbooks/remove/02-remove-edgenodes.yml
# "--==You must manually Remove NSX on ALL NSX Transport Node clusters before continuing==--"
- import_playbook: playbooks/remove/03-remove-nsxmanager-transportnodesprofiles.yml
- import_playbook: playbooks/remove/04-remove-nsxmanager-transportzones.yml
- import_playbook: playbooks/remove/05-remove-nsxmanager-ippools.yml
- import_playbook: playbooks/remove/06-remove-nsxmanager-uplinkprofiles.yml
- import_playbook: playbooks/remove/07-remove-compute-managers.yml
- import_playbook: playbooks/remove/08-remove-nsxmanager-vip.yml
# "--==You must manually Remove NSX Managers from cluster==--"
...
